README.md, package.json, src/index.js, src/utils/Component/index.js, src/utils/Component/showComponent.js, src/utils/Component/showComponent.test.js, src/utils/Data/getSourceData.js, src/utils/Data/getSourceData.test.js, src/utils/Data/index.js, src/utils/index.js, src/utils/meetsCondition.js, src/utils/meetsCondition.test.js
Mechanism for determining whether a field should be shown or not, based on the value of one or more other fields.
https://support.cop.homeoffice.gov.uk/browse/COP-9029
This should be covered by the unit tests within this commit. For the benefit of the QA team, this will be demonstrable within the Storybook stories in a subsequent PR.
=> COP-9029: Show and hide logic for components

src/components/FormPage/FormPage.jsx, src/components/FormPage/FormPage.scss, src/components/FormPage/FormPage.stories.mdx, src/components/FormPage/FormPage.test.js, src/components/FormPage/index.js, src/components/PageActions/ActionButton.jsx, src/components/index.js
Added a `FormPage` component for rendering an entire page of a form, as described in the JSON, along with unit tests and Storybook stories.
This PR concludes the set for https://support.cop.homeoffice.gov.uk/browse/COP-9577.
The component has 100% unit test coverage and the rendering can be observed within the accompanying Storybook story.
=> COP-9577: Add FormPage component

package.json, src/utils/Component/getComponent.test.js, yarn.lock
Upgraded to version 0.6.0 of the COP React Components library. This included some changes to the headings so that there is always an `<h1 />` on the form, whether it is "large" or "extra large".
A single unit test has been updated, which was testing that a "medium" header used an `<h3 />` tag, which it no longer does - it's now an `<h2 />`.
=> Use version 0.6.0 of COP React Components

src/index.js, src/models/FormTypes.js, src/models/HubFormats.js, src/models/index.js
Added the `FormTypes` and `HubFormats` models, which are essentially enumerations that are used to indicate how the form should be set up.
=> COP-9700: Add FormTypes and HubFormats models

src/components/FormRenderer/helpers/getCYA.js, src/components/FormRenderer/helpers/getCYA.test.js, src/components/FormRenderer/helpers/getFormState.js, src/components/FormRenderer/helpers/getFormState.test.js, src/components/FormRenderer/helpers/getPage.js, src/components/FormRenderer/helpers/getPage.test.js, src/components/FormRenderer/helpers/index.js
Added helper functions to get the current render state of the form.
Covered by the accompanying unit tests.
=> COP-9700: Add helper functions for FormRenderer

src/components/FormRenderer/FormRenderer.jsx, src/json/userProfile.json, src/utils/Format/formatDataForForm.js, src/utils/Format/formatDataForForm.test.js, src/utils/Format/formatDataForPage.js, src/utils/Format/formatDataForPage.test.js, src/utils/Format/index.js
Format the value of the entire form (or individual pages) for a specified event - i.e., the data can be formatted on blur, on submit, etc.
The `FormRenderer` now invokes this formatting at the point of submission.
Covered by accompanying unit tests. You can also see this by going to the Storybook stories and editing the line manager. Set it to be uppercase (or mixed case) and you will see that it formats it to lowercase on submission.
=> COP-9748: Format form

src/utils/Validate/index.js, src/utils/Validate/validateComponent.js, src/utils/Validate/validateComponent.test.js, src/utils/Validate/validateEmail.js, src/utils/Validate/validateEmail.test.js, src/utils/Validate/validatePage.test.js
Added a validation mechanism for email addresses. It specifically validates Home Office email addresses and will consider anything else to be invalid. This is invoked on any email components when the page is submitted.
https://support.cop.homeoffice.gov.uk/browse/COP-9136
Unit tests have been added to test for this behaviour accordingly and it will be visible within any Storybook stories that include email addresses.
=> COP-9136: Add email address validation

src/components/FormRenderer/helpers/canCYASubmit.js, src/components/FormRenderer/helpers/canCYASubmit.test.js, src/components/FormRenderer/helpers/index.js
Added a utility function that iterates through a set of pages to determine if they're all valid. If so, it returns `true`; if not, it returns `false` and calls an `onError` method with the array of errors across all of the pages.
=> COP-9746: Add util function for determining if CYA can be submitted

src/components/FormRenderer/helpers/getNextPageId.js, src/components/FormRenderer/helpers/getNextPageId.test.js, src/components/FormRenderer/helpers/index.js, src/models/FormPages.js, src/models/PageAction.js, src/models/index.js
Added a helper method to determine what should be the next page, depending on the type of form being rendered, the current page, and which action has just been invoked (if any). Also added two new types to support this functionality.
Covered by the accompanying unit tests.
=> COP-9746: Add helper method to determine the next page

src/components/FormPage/FormPage.test.js, src/components/PageActions/ActionButton.jsx, src/components/PageActions/ActionButton.test.js, src/components/PageActions/PageActions.test.js
Adjusted the logic around the `ActionButton` component to support additional types, such as a start button, and leverage `PageAction` logic recently added.
The accompanying unit tests have been updated.
=> COP-9746: Support additional action button types

src/hooks/useHooks.js
Added a hook for when the form is complete. It's expected that this will only fire on a "Check your answers" form as it's the only one with a genuine end state - the other form types will have appropriate completion actions on their page(s).
The unit tests already cover the functionality for changing the hook and this PR doesn't include _use_ of the hook - that will be covered elsewhere.
=> COP-9746: Add onFormComplete hook

src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/helpers/getCYA.js, src/components/FormRenderer/helpers/getCYA.test.js, src/components/FormRenderer/helpers/getFormState.test.js, src/components/FormRenderer/helpers/getPage.js, src/components/FormRenderer/helpers/getPage.test.js
Use the new `FormPages` model, getting rid of hard-coded `'hub'` values and incorrect use of `HubFormats` for page ids.
Covered by the accompanying unit test changes.
=> COP-9746: Refactor FormState logic

src/components/CheckYourAnswers/CheckYourAnswers.jsx, src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx, src/json/firstForm.json
Rather than simply offering a generic "Submit" on the **Check your answers** screen, allow custom actions from the JSON, just like any other page.
The `cya` object in the JSON can contain an `actions` property, which will dictate which buttons (if any) get shown at the bottom of the **Check your answers** screen. If there is no `actions` property (or it is an empty array), no buttons should be shown.
=> COP-9746: Allow custom actions for Check your answers

package.json, src/models/ComponentTypes.js, src/utils/Component/getComponent.js, src/utils/Component/getComponent.test.js, src/utils/Component/isEditable.js
Add support for DateInput components, which is now available in the COP React Components library.
**To test**
A unit test has been added to make sure the component is appropriately rendered from a JSON snippet. In addition, it's testable within the Storybook Sandbox.
=> EAB-85 Add date component

package.json, src/docs/FormTypes.stories.mdx, src/docs/Sandbox.stories.mdx, src/utils/CheckYourAnswers/getCYARow.js
A little bit of refactoring in one of the functions to clean up the setting of a `value` property (so it's not a mess of ternary operators and `||`s). Also sorted out some Storybook stories.
Finally, got rid of the pre-release suffix on the version as this should now be in a releasable state (`-alpha` is what I've been using to test things within COP UI).
There's nothing here to test - the unit tests for the utility function continue to pass.
=> Chore: Code cleanup

package.json, src/components/FormRenderer/handlers/getPageId.js, src/components/FormRenderer/handlers/getPageId.test.js, src/components/FormRenderer/handlers/handlers.test.js, src/components/PageActions/PageActions.stories.mdx, src/components/PageActions/PageActions.test.js, src/components/SummaryList/RowAction.jsx, src/components/SummaryList/RowAction.test.js, src/components/SummaryList/SummaryList.jsx, src/components/SummaryList/helpers/getRowActionAttributes.js, src/components/SummaryList/helpers/getRowActionAttributes.test.js, src/docs/Page.stories.mdx, src/docs/PageExamples.stories.mdx, src/json/firstForm.json, src/json/saveAndContinue.json, src/json/userProfile.json, src/utils/CheckYourAnswers/getCYAAction.js, src/utils/CheckYourAnswers/getCYAAction.test.js, src/utils/CheckYourAnswers/getCYARow.js, yarn.lock
Refactored page actions and the **Check your answers** links to use `page` as a property rather than mixing and matching `href` and `url`. We presently only ever navigate internally within the form so `page` makes the most sense. This refactor is necessary for saving the form status in a later PR.
https://support.cop.homeoffice.gov.uk/browse/COP-10035
All of the affected unit tests have been updated, as have the various Storybook stories and JSON files. You can test this by making sure that you can still navigate around within the form in Storybook.
This is a major release due to the refactor - existing JSON files (of which there should be almost none in the wild) - will need to be adjusted along the lines of:
```
"pages" : [
{
...
"actions": [
{ "type": "navigate", "label": "Next", …
```
=> COP-10035: Refactor actions

src/utils/CheckYourAnswers/getCYAAction.js, src/utils/CheckYourAnswers/getCYAAction.test.js, src/utils/FormPage/getFormPage.js, src/utils/FormPage/getPageActions.js, src/utils/FormPage/getPageActions.test.js
Added utility functions to standardise Page and CYA actions and offer backwards compatibility with version 1.x of the Form Renderer, which used `href` and `url`. Both now just use `page`.
This should be covered by the accompanying unit tests.
=> COP-10241: Support url and href on Page and CYA actions

package.json, src/components/FormPage/FormPage.test.js, src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/helpers/getNextPageId.js, src/components/FormRenderer/helpers/getNextPageId.test.js, src/utils/Validate/validateComponent.js, yarn.lock
Fixed the logic for determining the next page in the form, which now properly assesses the state of the data captured on the form to see whether a page's visibility is affected by it.
Covered by accompanying unit tests. You can see the behaviour in the Sandbox, though, by setting up a form with 3 pages and making the 2nd page only show if a field on the first page has a particular value. Previously, it would have just shown the 2nd page anyway; now it will skip to the next page and see if _that_ one should be shown... all the way to the end of the CYA screen if appropriate.
=> COP-10241: Fix logic for determining the next form page

src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/helpers/getSubmissionStatus.js, src/components/FormRenderer/helpers/getSubmissionStatus.test.js, src/components/FormRenderer/helpers/index.js
Added a utility function to set up the status of the form, which is added to the payload at the point of saving in a `formStatus` variable.
Correspondingly, when the form initially loads, the renderer will navigate to the appropriate page if it encounters a `data.formStatus` object. Otherwise, it will default to the "first" page, as determined by the form type.
Covered by accompanying unit tests, but you can also see the behaviour of navigating straight to the correct "return page" in the Sandbox if you set up the initial data to include a property that looks like this:
```
"formStatus": {
"page": "the_id_of_one_of_the_pages"
}
```
=> COP-10241: Save and use form status

src/docs/Component.stories.mdx, src/utils/Validate/validateComponent.js, src/utils/Validate/validateRequired.js, src/utils/Validate/validateRequired.test.js
Designs for new EAB screens require a variety of error messages to be displayed when required validation is failed. This PR adds the capability to specify custom messages for this purpose in the JSON.
=> EAB-142 Add custom required error messages

package.json, src/components/CheckYourAnswers/CheckYourAnswers.jsx, src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx, src/components/CheckYourAnswers/CheckYourAnswers.test.js, src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/FormRenderer.stories.mdx, src/components/FormRenderer/FormRenderer.test.js, src/components/SummaryList/SummaryList.jsx, src/components/SummaryList/SummaryList.scss, src/components/SummaryList/SummaryList.stories.mdx, src/components/SummaryList/SummaryList.test.js, src/index.js
This change has been done to support changes in cop to display read-only versions of submitted forms when in CaseView. The styling has been applied to match what was outlined in the figma documentation containing the initial designs of CaseView.
https://support.cop.homeoffice.gov.uk/browse/COP-10344
Testing that the functionality works can be achieved by viewing the changes in storybook (`yarn storybook`) and looking in each of the respected sections for Check Your Answers, Form Renderer and Summary List. At the bottom there will be a read-only view which contains no change actions, or no lines.
=> Feature/cop 10344/caseview v3

package.json, src/components/FormComponent/FormComponent.jsx, src/components/FormComponent/FormComponent.test.js, src/hooks/useHooks.js, src/utils/Component/getComponent.js
Added a hook for overriding components. The override function is passed the `wrap` parameter where a value of `false` means it _shouldn't_ be wrapped and a value of `true` means the function should decide whether or not it's should be within a `FormGroup` and wrap it if necessary.
https://support.cop.homeoffice.gov.uk/browse/COP-10564
=> COP-10564: Add hook for overriding component

src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/FormRenderer.test.js, src/components/FormRenderer/helpers/getSubmissionStatus.js, src/components/FormRenderer/helpers/getSubmissionStatus.test.js, src/components/FormRenderer/helpers/getUpdatedSectionStates.js, src/components/FormRenderer/helpers/getUpdatedSectionStates.test.js, src/components/FormRenderer/helpers/index.js, src/components/TaskList/Task.jsx
Add management of the state of each task. The task state can be 'Cannot Start', 'Not Started, 'In Progress' or 'Complete'. This information is stored in the backend and updated as the user progresses through the task list. Details for when tasks should be in each state and progress to the next one are covered in the jira ticket. 
The updates to `FormRenderer.jsx` largely cover the updating of states when the user either moves to the next page or completes a section. This uses the new helper function `getUpdatedSectionStates()` to determine each tasks state and an updated `getSubmissionStatus()` to add state information to the submitted data object.
Covered by unit tests
=> COP-9885 Add task state management

src/utils/CheckYourAnswers/getCYARowsForContainer.js, src/utils/CheckYourAnswers/getCYARowsForContainer.test.js, src/utils/CheckYourAnswers/getCYARowsForPage.js, src/utils/CheckYourAnswers/getCYARowsForPage.test.js, src/utils/CheckYourAnswers/showComponentCYA.js
Support `Container` components on the **Check your answers** screen. Presently, each editable component within a `Container` will be handled exactly the same as if it was at the top level of the form.
https://support.cop.homeoffice.gov.uk/browse/COP-10558
=> COP-10558: Support containers on Check your answers screen

package.json, src/components/FormComponent/FormComponent.jsx, yarn.lock
Fixed an issue with the `FormComponent.jsx` file, which wasn't importing `React` despite including JSX markup. This meant that importing version 2.6.0 and trying to run anything that included the `FormComponent` would throw an exception - i.e., placing a `<FormRenderer>` element on a page or within another component would fail, which is rather fatal.
=> COP-10567: Fix cerberus import issue

package.json, src/components/CheckYourAnswers/Answer.jsx, src/components/CheckYourAnswers/Answer.test.js, src/components/CheckYourAnswers/CheckYourAnswers.test.js, src/components/SummaryList/SummaryList.jsx, src/components/SummaryList/SummaryList.test.js
Added `(optional)` to the key in check your answers screen when fields are not set to `required:true`. Also added a `VisuallyHidden` component to the check answers screen when optional questions are not filled in. Unit tests have been modified to reflect those changes
https://support.cop.homeoffice.gov.uk/browse/COP-10811
**To test**
Covered by unit tests.
=> added optional description text and screen reader text for blank answers

src/models/ComponentTypes.js, src/utils/Validate/validateCollection.js, src/utils/Validate/validateCollection.test.js, src/utils/Validate/validateComponent.js, src/utils/Validate/validateComponent.test.js, src/utils/Validate/validateContainer.js, src/utils/Validate/validateContainer.test.js
Added validation for collections and also refactored the `validateComponent` and `validateContainer` methods so they're in their own files, rather than all bundled into one.
=> COP-10873: Add collection validation

src/components/SummaryList/SummaryList.jsx, src/models/CollectionLabels.js, src/models/index.js, src/setupTests.js, src/utils/CheckYourAnswers/getCYARow.js, src/utils/CheckYourAnswers/getCYARow.test.js, src/utils/CheckYourAnswers/getCYARowsForCollection.js, src/utils/CheckYourAnswers/getCYARowsForCollection.test.js, src/utils/CheckYourAnswers/getCYARowsForContainer.test.js, src/utils/CheckYourAnswers/getCYARowsForPage.js, src/utils/CheckYourAnswers/getCYARowsForPage.test.js
Added a utility function to get Check your answers rows for collections of items. This also necessitated some changes to other utility functions for getting CYA rows.
=> Add util function to get CYA rows for collection

src/components/CheckYourAnswers/CheckYourAnswers.jsx, src/components/CheckYourAnswers/CheckYourAnswers.test.js, src/components/FormComponent/FormComponent.jsx, src/components/FormComponent/FormComponent.test.js, src/components/FormPage/FormPage.jsx, src/components/FormPage/FormPage.test.js, src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/helpers/canActionProceed.js, src/components/FormRenderer/helpers/canActionProceed.test.js, src/components/FormRenderer/helpers/canCYASubmit.js, src/components/FormRenderer/helpers/canCYASubmit.test.js, src/index.js, src/setupTests.js
The `FormRenderer` component has been refactored to wrap an `InternalFormRenderer` component inside of a `ValidationContextProvider`, which handles errors and validation across the form now.
This has removed the need for holding onto error states in the form JSON, which made it much harder to track and manage - errors and validation are now accessed within components via a `useValidation()` hook.
Covered by accompanying unit tests, which have all been updated appropriately.
=> COP-10873: Refactor validation

src/context/ValidationContext/ValidationContext.jsx
While running tests for cop-ui there was an error reporting that React was not defined and a stack trace ending in the ValidationContext jsx file in the renderer.  The fix was to import React from react within that file.
=> Import React in ValidationContext.jsx

src/components/CheckYourAnswers/Answer.test.js, src/components/FormComponent/FormComponent.test.js, src/components/FormRenderer/FormRenderer.jsx, src/context/HooksContext/HooksContext.test.js, src/hooks/useAxios.test.js, src/hooks/useGetRequest.test.js, src/hooks/useHooks.js, src/hooks/useHooks.test.js, src/hooks/useRefData.test.js, src/utils/CheckYourAnswers/getCYARowForGroup.test.js, src/utils/CheckYourAnswers/getCYARowsForPage.test.js
`useHooks` is now a pass-through for the `HooksContext`, which makes all of the hooks instance-specific.
Updated a bunch of unit tests so that they're now wrapping testable components inside of a `<HooksContextProvider />` element where they have `useHooks` internally.
https://support.cop.homeoffice.gov.uk/browse/COP-10947
Covered by accompanying and updated unit tests.
=> COP-10947: Refactor useHooks

src/components/CheckYourAnswers/Answer.test.js, src/components/FormComponent/FormComponent.test.js, src/components/FormRenderer/FormRenderer.jsx, src/context/HooksContext/HooksContext.jsx, src/context/HooksContext/HooksContext.test.js, src/context/HooksContext/index.js, src/context/index.js, src/hooks/useAxios.test.js, src/hooks/useGetRequest.test.js, src/hooks/useHooks.js, src/hooks/useHooks.test.js, src/hooks/useRefData.test.js, src/setupTests.js, src/utils/CheckYourAnswers/getCYARowForGroup.test.js, src/utils/CheckYourAnswers/getCYARowsForPage.test.js
Added a `HooksContext` and `HooksContextProvider`, which will replace the functionality previously implemented directly by `useHooks`.
https://support.cop.homeoffice.gov.uk/browse/COP-10947
Accompanying unit tests will be included in the next PR - it's not in this one directly simply because it leverages the refactored `useHooks` hook... but including that in this PR means all of the _other_ components and tests that need `useHooks` will also need to be included, and then it's a big PR.
=> COP-10947: Add hooks context

package.json, src/components/CheckYourAnswers/Answer.test.js, src/components/FormComponent/FormComponent.test.js, src/components/FormRenderer/FormRenderer.jsx, src/components/FormRenderer/FormRenderer.stories.mdx, src/context/HooksContext/HooksContext.jsx, src/context/HooksContext/HooksContext.test.js, src/context/HooksContext/index.js, src/context/index.js, src/docs/Sandbox.stories.mdx, src/hooks/useAxios.test.js, src/hooks/useGetRequest.test.js, src/hooks/useHooks.js, src/hooks/useHooks.test.js, src/hooks/useRefData.test.js, src/index.js, src/index.test.js, src/setupTests.js, src/utils/CheckYourAnswers/getCYARowForGroup.test.js, src/utils/CheckYourAnswers/getCYARowsForPage.test.js
Stop exposing the `intercepts` in the library and stop using `addHook` in the storybook stories, ahead of a refactor of the hooks mechanism.
https://support.cop.homeoffice.gov.uk/browse/COP-10947
If the Storybook stories still run, it's working fine.
=> COP-10947: Stop exposing intercepts

src/utils/Validate/index.js, src/utils/Validate/validateComponent.js, src/utils/Validate/validateRegex.js, src/utils/Validate/validateRegex.test.js
Added the ability to define regex validation for a component in the form renderer JSON files. Custom errors for when the regex validation failed can also now be defined.
Doing so looks like:
```
...
"type": "text",
"pattern": "^[a-z]*$",
"custom_errors": [
{
"type": "pattern",
"message": "Failed regex validation."
}
]
...
```
=> Implement regex validation for components.

package.json, src/utils/Component/getComponentTests/getComponent.date.test.js, yarn.lock
Use version 1.7.1 of component library, which fixes an issue with the `DateInput` component.
https://support.cop.homeoffice.gov.uk/browse/COP-10967
The following was broken in the COP React Form Renderer:
1. Set up the JSON to have a date field;
2. Set up the initial data to have a valid value for that date field;
3. Switch to the Preview tab and you'll see the value appropriately showing in the date field;
4. Go back to the initial date and change to another valid value for the date field;
5. Switch back to the Preview tab and you'll now see the value in the date field flicking between the old and new values.
This should now be fixed.
=> COP-10967: Use version 1.7.1 of component library

package.json, src/utils/Validate/validateCollection.js, src/utils/Validate/validateComponent.js, src/utils/Validate/validateContainer.js, src/utils/Validate/validatePage.js
Added support for validation of conditionally-shown components within collections. Previously, any conditionally-shown components within collections were simply considered _not_ to be shown, which meant they weren't validated.
Within the Form Renderer Sandbox, set up a form with a collection that contains a conditionally-shown field. Make sure the validation on that field kicks in when it is shown and the validation is ignored when it's _not_ shown.
=> COP-10873: Improve collection validation

package.json, src/context/HooksContext/HooksContext.jsx
While running tests for cop-ui there was an error reporting that React was not defined and a stack trace ending in the HooksContext jsx file in the renderer. The fix was to import React from react within that file.
=> Add React import to Hooks Context

package.json, src/utils/Component/getComponent.js, src/utils/Component/getComponentTests/getComponent.time.test.js, src/utils/Component/wrapInFormGroup.js, yarn.lock
Using version `"1.7.4"` of the component library, which includes the fixed `<TimeInput />` component. Also added some unit tests for the time input.
https://support.cop.homeoffice.gov.uk/browse/COP-10967
This is the broken behaviour, so make sure it's no longer happening in the Form Renderer Storybook:
1. Set up the JSON to have a time field;
2. Set up the initial data to have a valid value for that time field;
3. Switch to the Preview tab and you'll see the value appropriately showing in the time field;
4. Go back to the initial data and change to another valid value for the time field;
5. Switch back to the Preview tab and you'll now see the value in the time field flicking between the old and new values.
=> COP-10967: Fix for time input

package.json, src/utils/CheckYourAnswers/getCYARow.js, src/utils/CheckYourAnswers/getCYARow.test.js, src/utils/Validate/validateComponent.js, src/utils/Validate/validateComponent.test.js
Fixed an issue with an undefined `page.formData` when showing the CYA screen (hub-and-spoke form type) when the form contains a `<Checkboxes />` component.
Added a unit test to make sure it now behaves itself.
=> Fix bugs with option nested values

package.json, src/components/FormComponent/FormComponent.jsx, src/utils/Data/getOptions.js
Radio buttons have the option to have strings like 'or' between them, this is a fix to make them work again
=> Fix option to have strings between radios

package.json, src/docs/ComponentExamples.stories.mdx, src/docs/ComponentTypes.stories.mdx, src/models/ComponentTypes.js, src/utils/Component/getComponent.js, src/utils/Component/getComponentTests/getComponent.warningText.test.js, yarn.lock
Description: 
Addition of new component "warning" to display a warning message to the user. Cop components dependency has been updated to include new component and storybook documentation added.
To Test: 
1. Create a new form with a component of type "warning-text".
2. Verify that the component is correctly displayed and is in line with GDS. (https://design-system.service.gov.uk/components/warning-text/)
3. Verify that "content" provided is accurately displayed inside the warning text component.
Example JSON
{
"type": "warning",
"content": "Your warning message here"
}
Jira Ticket - https://support.cop.homeoffice.gov.uk/browse/CO-2173
=> CO-2173: warning text

package.json, src/utils/Validate/validatePage.js
A bug was introduced as part of interpolating error messages, which didn't account for collections and containers properly.
This shouldn't be merged with the pre-release suffix on the version.
=> BUG: Fix issue with page validation

package.json, src/hooks/useRefData.js, src/hooks/useRefData.test.js, src/utils/Data/refDataToOptions.js, src/utils/Data/refDataToOptions.test.js, src/utils/Data/setupRefDataUrlForComponent.js, src/utils/Data/setupRefDataUrlForComponent.test.js, src/utils/FormPage/getFormPage.js, src/utils/FormPage/getFormPage.test.js
Added support for a custom item structure for reference data options that are returned, along with support for numeric identifiers that should be used as option values.
https://support.cop.homeoffice.gov.uk/browse/COP-10220
Covered by accompanying unit tests, but this will also be visible when setting up a form with differently structured reference data, such as the TIS ([COP-10220](https://support.cop.homeoffice.gov.uk/browse/COP-10220)).
=> COP-10220: Improve support for refdata options

package.json, src/components/FormPage/FormPage.jsx, src/components/FormRenderer/FormRenderer.jsx
This is a fix/workaround for anchor links in the `ErrorSummary` component wiping a pages `formData` when clicked on.
The suggested changes just reapply a pages `patch` data to its `formData` before validation. Values for components within the page are also now only taken from `formData` if no value exists for them in `patch`.
=> CI-130 Added a fix for formData getting wiped

src/components/FormPage/FormPage.jsx
The JIRA ticket for this issue is [EAB-691](https://support.cop.homeoffice.gov.uk/browse/EAB-691).
This is the same issue that was solved for regular components in [CI-130](https://support.cop.homeoffice.gov.uk/browse/CI-130). The previous fix didn't account for nested components.
The `formData` passed to a component is now merged with a component's `patch` data. This will replace any missing nested values if they are present in `patch`.
=> EAB-691 Fixed clicking an ErrorSummary link wiping nested components

src/utils/Component/getComponent.js
Added support for a default value to be supplied in a Form Renderer JSON file for any DateInput component. Any date string in the format `DD-MM-YYYY` is supported. Using the word `today` instead of a date string will cause Form Renderer to supply today's date, in the form `DD-MM-YYYY`, as the default value.
To test this functionality, define a date component in the Form Renderer sandbox and add the field:
```
...
"defaultValue": "01-01-2022",
...
```
or
```
...
"defaultValue": "today",
...
```
=> EAB-628 Added support for pre-populating date inputs with today's date

package.json, src/docs/ConditionalDisplayExamples.stories.mdx, src/utils/Condition/meetsCondition.js, src/utils/Condition/meetsCondition.test.js
show_when can now be passed on a component or page with the `contains` operator. This is different to the `in` operator in that the in operator is used to pass an array of accepted values that a given field is "in", whereas `contains` is used to pass a single accepted value which is "in" a field.
Covered by accompanying unit tests. Functionality can be tested in the Form Renderer Sandbox by adding a component with a show_when with "op": "contains".
1. Add an array field to the `initial data` tab in form renderer sandbox. e.g. "something" : ["alpha", "bravo", "charlie" ]
2. use the below component and confirm that it is displayed
```
{
"id": "status",
"fieldId": "status",
"type": "text",
"label": "select status",
"required": true,
"show_when": [
{
"field": "something",
"op": "contains", …
```
=> Added support for "contains" operator on conditional display

package.json, yarn.lock
Following merge of https://github.com/UKHomeOffice/cop-react-components/pull/108
=> Update cop-react-components to version 1.10.0
