UKHomeOffice/cop-react-form-renderer

- src/json/userProfile.data.json
- src/json/userProfile.json
- src/utils/Data/index.js
- src/utils/Data/setupFormData.js
- src/utils/Data/setupFormData.test.js
Added functions and unit tests for loading form data.
https://support.cop.homeoffice.gov.uk/browse/COP-9576
This is covered by unit tests and will be able to be seen in anger within the Storybook stories in a later PR.
> COP-9576: Pre-load data

- src/utils/FormPage/getFormPage.js
- src/utils/FormPage/getFormPage.test.js
- src/utils/FormPage/getFormPages.js
- src/utils/FormPage/getFormPages.test.js
- src/utils/FormPage/getParagraphFromText.js
- src/utils/FormPage/getParagraphFromText.test.js
- src/utils/FormPage/index.js
- src/utils/FormPage/useComponent.js
- src/utils/FormPage/useComponent.test.js
- src/utils/index.js
Utility functions and unit tests for setting up pages.
https://support.cop.homeoffice.gov.uk/browse/COP-9577
> COP-9577: Add utility functions for setting up pages

- src/components/FormRenderer/FormRenderer.stories.mdx
- src/docs/Component.stories.mdx
- src/docs/ComponentExamples.stories.mdx
- src/docs/ComponentTypes.stories.mdx
- src/docs/ConditionalDisplayExamples.stories.mdx
- src/docs/EditableComponents.stories.mdx
- src/docs/Form.stories.mdx
- src/docs/FormTypes.stories.mdx
- src/docs/Page.stories.mdx
- src/docs/PageExamples.stories.mdx
Storybook stories that document the structure of the JSON used for rendering forms within the COP React Form Renderer, including descriptions of what each property is for, its type, and valid values where appropriate.
There are also a number of examples, particularly for the different component types.
https://support.cop.homeoffice.gov.uk/browse/COP-9048
> COP-9048: Document JSON structure

- src/components/PageActions/ActionButton.jsx
- src/components/PageActions/ActionButton.test.js
- src/components/PageActions/PageActions.jsx
- src/components/PageActions/PageActions.stories.mdx
- src/components/PageActions/PageActions.test.js
- src/components/PageActions/index.js
Added the `PageActions` and accompanying `ActionButton` components, along with unit tests.
These are displayed at the bottom of a page, based on the `"actions"` property within the JSON.
Both components in this PR have 100% unit test coverage.
> COP-9577: Add PageActions component

- .storybook/manager.js
- .storybook/preview.js
Ordered the Storybook stories in a more logical way, rather than allowing it to be purely alphabetical.
> Order Storybook stories

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.scss
- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/CheckYourAnswers/index.js
- src/components/index.js
- src/json/userProfile.data.json
Added the `CheckYourAnswers` component that wraps up a bunch of other components for rendering the answers from the pages of a form (unless they should be hidden) and offers mechanisms to change those displayed answers.
Covered by accompanying unit tests and Storybook stories.
> COP-9578: Add CheckYourAnswers component

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.scss
- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/CheckYourAnswers/index.js
- src/components/index.js
- src/json/userProfile.data.json
- src/utils/CheckYourAnswers/getCYARowsForPage.js
- src/utils/CheckYourAnswers/getCYARowsForPage.test.js
- src/utils/CheckYourAnswers/index.js
- src/utils/index.js
Added a utility function for displaying all appropriate (and visible) rows on the Check your answers screen for a given page.
> COP-9578: Add util function for CYA page rows

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.scss
- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/CheckYourAnswers/index.js
- src/components/index.js
- src/json/userProfile.data.json
- src/utils/CheckYourAnswers/getCYARow.js
- src/utils/CheckYourAnswers/getCYARow.test.js
- src/utils/CheckYourAnswers/getCYARowsForPage.js
- src/utils/CheckYourAnswers/getCYARowsForPage.test.js
- src/utils/CheckYourAnswers/index.js
- src/utils/index.js
Added a utility function for displaying an appropriate row on the Check your answers screen for a given component.
> COP-9578: Add util function for CYA row

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.scss
- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/CheckYourAnswers/index.js
- src/components/index.js
- src/json/userProfile.data.json
- src/utils/CheckYourAnswers/getCYAAction.js
- src/utils/CheckYourAnswers/getCYAAction.test.js
- src/utils/CheckYourAnswers/getCYARow.js
- src/utils/CheckYourAnswers/getCYARow.test.js
- src/utils/CheckYourAnswers/getCYARowsForPage.js
- src/utils/CheckYourAnswers/getCYARowsForPage.test.js
- src/utils/CheckYourAnswers/index.js
- src/utils/index.js
Added a utility function for displaying an appropriate "Change" link on the Check your answers screen for a given component.
> COP-9578: Add util function for CYA "Change" link

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.scss
- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/CheckYourAnswers/index.js
- src/components/index.js
- src/json/userProfile.data.json
- src/utils/CheckYourAnswers/getCYAAction.js
- src/utils/CheckYourAnswers/getCYAAction.test.js
- src/utils/CheckYourAnswers/getCYARow.js
- src/utils/CheckYourAnswers/getCYARow.test.js
- src/utils/CheckYourAnswers/getCYARowsForPage.js
- src/utils/CheckYourAnswers/getCYARowsForPage.test.js
- src/utils/CheckYourAnswers/index.js
- src/utils/CheckYourAnswers/showComponentCYA.js
- src/utils/CheckYourAnswers/showComponentCYA.test.js
- src/utils/index.js
Added a utility function to determine whether or not a given component should display on the **Check your answers** screen.
> COP-9578: Add util function for showing a component on CYA

- src/docs/Form.stories.mdx
- src/docs/FormExamples.stories.mdx
Added a Storybook story for form examples.
> COP-9555: Add form examples to documentation

- src/utils/Hub/getFormHub.js
- src/utils/Hub/getFormHub.test.js
- src/utils/Hub/index.js
- src/utils/index.js
Added a utility function to get the appropriate hub configuration for a form.
This is covered by the accompanying unit tests.
> COP-9700: Add utility function to get the hub

- src/hooks/useHooks.js
- src/hooks/useHooks.test.js
- src/index.js
Added hooks for `onFormLoad`, `onPageChange`, and `onSubmit`.
> COP-9700: Add additional hooks

- src/components/FormRenderer/handlers/cyaAction.js
- src/components/FormRenderer/handlers/getPageId.js
- src/components/FormRenderer/handlers/getPageId.test.js
- src/components/FormRenderer/handlers/handlers.test.js
- src/components/FormRenderer/handlers/index.js
- src/components/FormRenderer/handlers/navigate.js
- src/components/FormRenderer/handlers/submissionError.js
- src/hooks/useHooks.js
- src/hooks/useHooks.test.js
- src/index.js
Added handler methods for the `FormRenderer` component to deal with invocations of Check your answers and Page actions, as well as submission errors.
Covered by the accompanying unit tests.
> COP-9700: Add FormRenderer handler methods

- src/components/FormRenderer/handlers/getPageId.js
- src/components/FormRenderer/handlers/getPageId.test.js
Actions on the CYA screen have an href but on a page have a url. Both need to be supported.
> COP-9700: Support action url

- src/components/FormRenderer/FormRenderer.jsx
- src/components/FormRenderer/FormRenderer.scss
- src/components/FormRenderer/FormRenderer.stories.mdx
- src/components/FormRenderer/FormRenderer.test.js
- src/components/FormRenderer/index.js
- src/components/index.js
- src/index.js
- src/index.test.js
Added the `FormRenderer` component, which ties all of the other components together.
Covered by the accompanying unit tests and Storybook stories.
> COP-9700: Add FormRenderer component

- src/models/EventTypes.js
- src/models/index.js
- src/utils/Format/formatDataForComponent.js
- src/utils/Format/formatDataForComponent.test.js
- src/utils/Format/index.js
Format the value of a component for a specified event - i.e., the data can be formatted on blur, on submit, etc.
> COP-9748: Format component value

- package.json
- src/docs/Sandbox.stories.mdx
- src/docs/Sandbox.stories.scss
- src/json/saveAndContinue.json
- yarn.lock
Added a sandbox Storybook story that allows users to set their own form JSON and initial data to see how that plays out on the form renderer.
1. Run the following:
```
$ yarn install
$ yarn storybook
```
2. Navigate to **Components > Sandbox**;
3. Edit the JSON within the **Form JSON** tab.
4. Switch back to **Preview** and you should see your changes have taken effect.
**Note:** The JSON can be copied directly out of the editor but reloading the page or switching stories will clear your changes.
> COP-9699: Add sandbox for testing JSON

- src/components/CheckYourAnswers/CheckYourAnswers.stories.mdx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/FormComponent/FormComponent.stories.mdx
- src/components/FormPage/FormPage.stories.mdx
- src/components/FormRenderer/FormRenderer.stories.mdx
- src/components/FormRenderer/FormRenderer.test.js
- src/docs/ComponentExamples.stories.mdx
- src/docs/Sandbox.stories.mdx
- src/json/userProfile.data.json
- src/json/userProfile.json
- src/utils/Data/setupFormData.test.js
- src/utils/Data/setupRefDataUrlForComponent.test.js
- src/utils/FormPage/getFormPage.js
- src/utils/FormPage/getFormPage.test.js
- src/utils/FormPage/getFormPages.test.js
- src/utils/Hub/getFormHub.test.js
The initial data structure has changed to remove the various contexts and replace them with something cleaner. This was specifically requested following the initial deployment last week.
If all of the Storybook stories still work then this has succeeded. There are no coding changes.
> Change JSON data structure

- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/FormRenderer/FormRenderer.jsx
- src/components/FormRenderer/FormRenderer.stories.mdx
- src/components/FormRenderer/FormRenderer.test.js
- src/json/firstForm.json
Added a mechanism for rendering action buttons and handling actions on the Check your answers screen in order to support the mechanism of submitting in the "CYA" form type.
Somewhat covered by accompanying unit tests, also somewhat covered by the newly-added Storybook story. Ultimately, though, this will all be seen in the consuming application (COP UI).
> COP-9746: Add actions to Check your answers screen

- src/components/index.js
- src/docs/Sandbox.stories.mdx
- src/docs/Sandbox.stories.scss
Added local storage in the Sandbox and made it more usable overall.
There are no unit tests for this as it's part of Storybook... but you can test it by:
```
$ yarn install
$ yarn storybook
```
This should open a browser tab for you at http://localhost:6007 automatically but if not, you can go to that address yourself and then select "Sandbox" from the left-hand menu to try it out.
> Improve sandbox functionality

- src/components/FormPage/FormPage.test.js
- src/components/FormRenderer/FormRenderer.jsx
- src/components/PageActions/ActionButton.test.js
- src/components/PageActions/PageActions.test.js
- src/hooks/useHooks.test.js
- src/models/PageAction.js
Use the exported `PageAction` constants rather than hard-coded strings all over the place.
> Use PageAction constants

- package.json
- src/docs/Page.stories.mdx
- src/utils/CheckYourAnswers/getCYARowsForPage.js
- src/utils/FormPage/getEditableComponents.js
- src/utils/FormPage/getEditableComponents.test.js
- src/utils/FormPage/index.js
- src/utils/FormPage/showFormPage.js
- src/utils/FormPage/showFormPage.test.js
Added utility functions that determine whether or not a page should be shown, using the same `show_when` mechanism as for components.
> COP-10241: Form status utilities

- LICENSE
- README.md
Add a LICENSE file and information about the MIT licence this library can be used under.
> Add MIT licence

- package.json
- src/docs/ComponentExamples.stories.mdx
- src/docs/ComponentTypes.stories.mdx
- src/docs/EditableComponents.stories.mdx
- src/models/ComponentTypes.js
- src/utils/Component/getComponent.js
- src/utils/Component/getComponentTests/getComponent.file.test.js
- src/utils/Component/isEditable.js
- yarn.lock
Added support for the component type "file", which will render a `<FileUpload />` element from the component library.
Also added unit tests and to the Storybook documentation for this new type.
https://support.cop.homeoffice.gov.uk/browse/COP-10567
Covered by unit tests.
> COP-10567: Add support for "file" component type

- package.json
- src/components/FormComponent/Container.test.js
- src/components/FormComponent/FormComponent.jsx
- src/utils/Data/index.js
- src/utils/Data/setDataItem.js
- src/utils/Data/setDataItem.test.js
- yarn.lock
When a file is selected for upload, the Form Renderer now internally adjusts the payload to include a `meta.documents` array with any files that have been selected.
This will allow any consuming application to interrogate the payload to determine when any files need to be uploaded and act appropriately.
https://support.cop.homeoffice.gov.uk/browse/COP-10219
Covered by accompanying unit tests and observable within the Sandbox if a component of type `"file"` is added to the Form JSON.
> COP-10219: Adjust payload for files

- package.json
- src/components/FormRenderer/FormRenderer.test.js
- src/components/PageActions/ActionButton.jsx
- src/json/taskList.json
Added label for `saveAndNavigate` buttons to show `Save and continue`
> added save and coninue label to tasklist saveAndNavigate

- package.json
- src/components/FormRenderer/FormRenderer.jsx
- src/components/FormRenderer/FormRenderer.test.js
**Description:**
Added the save and continue/save and return later buttons to tasklist check answer pages
> added save buttons to cya

- .storybook/decorators.jsx
- src/components/TaskList/TaskList.scss
Removed GDS Transport font from tasklist
> swapped gds transport for roboto in tasklist

- package.json
- src/components/TaskList/Task.jsx
Tasks should now be 'tabbable' using the keyboard
> added tabindex to tab links in tasklist

- package.json
- src/components/FormRenderer/helpers/getSubmissionStatus.js
- src/components/FormRenderer/helpers/getSubmissionStatus.test.js
Fixed behaviour for save and continue when returning to in-progress forms
> fixed save and continue behaviour in tasklist

- src/components/SummaryList/GroupAction.jsx
- src/components/SummaryList/SummaryList.jsx
- src/components/SummaryList/SummaryList.scss
- src/components/SummaryList/SummaryList.test.js
- src/components/SummaryList/SummaryListRow.jsx
- src/components/SummaryList/SummaryListTitleRow.jsx
Added support for collections in the Check your answers summary list.
Covered by accompanying unit tests, which have been added to and updated.
> COP-10873: Support collections in CYA summary list

- package.json
- src/components/CheckYourAnswers/CheckYourAnswers.jsx
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/components/FormComponent/Collection.jsx
- src/components/FormComponent/Collection.scss
- src/components/FormComponent/Container.jsx
- src/components/FormComponent/Container.test.js
- src/components/FormComponent/FormComponent.jsx
- src/components/FormComponent/FormComponent.test.js
- src/components/FormPage/FormPage.jsx
- src/components/FormPage/FormPage.test.js
- src/components/FormRenderer/FormRenderer.jsx
- src/components/FormRenderer/helpers/canActionProceed.js
- src/components/FormRenderer/helpers/canActionProceed.test.js
- src/components/FormRenderer/helpers/canCYASubmit.js
- src/components/FormRenderer/helpers/canCYASubmit.test.js
- src/index.js
- src/setupTests.js
Added a `Collection` component and, in the midst of this, moved `Container` to its own file, rather than having all 3 inside of `FormComponent`.
This refactor also leverages the Meta utils now, most of the code from which had previously sat inside of `FormComponent.jsx`.
Covered by accompanying unit tests (not yet present for the `Collection` component itself, but will be added soon.)
> Add Collection component

- package.json
- src/utils/Data/getSourceData.js
- src/utils/Data/getSourceData.test.js
Added support for getting source data from arrays.
> COP-10873: Add support for getting source data from arrays

- package.json
> increment version for bug

- package.json
Oops. Forgot to go up a patch version of the renderer itself! 🤦
> COP-10967: Update package.json

- package.json
- src/components/FormRenderer/FormRenderer.jsx
Reverting changes for submit type, following a chat with Paul this was deemed unnecessary.
> Revert previous changes

- package.json
- src/docs/ComponentExamples.stories.mdx
- src/docs/ComponentTypes.stories.mdx
- src/models/ComponentTypes.js
- src/utils/Component/getComponent.js
- src/utils/Component/getComponentTests/getComponent.details.test.js
Description:
Addition of new component "details" to display additional information to the user that may not be relevant to all users. Displays an initial "summary" which should describe what is in the "content" when the summary is clicked.
To Test:
Create a new form with a component of type "details".
Verify that the component is correctly displayed and is in line with GDS. (https://design-system.service.gov.uk/components/details/)
Verify that "content" provided is accurately displayed after clicking on the "summary" text.
Example JSON
{
"type": "details",
"summary": "Summary",
"content": "Additional information goes here"
}
Jira Ticket - https://support.cop.homeoffice.gov.uk/browse/CO-2174
Note: 'Date' has also been moved to the correct place in the storybook in this PR
> details component added - fixing issues with rebasing

- package.json
- src/components/CheckYourAnswers/CheckYourAnswers.test.js
- src/models/ComponentTypes.js
- src/utils/Component/getComponent.js
- src/utils/Component/getComponentTests/getComponent.select.test.js
- src/utils/Component/isEditable.js
- yarn.lock
This is to enable the use of the Select component, implemented in https://github.com/UKHomeOffice/cop-react-components/pull/98, within the Form Renderer.
> Feature/EAB-640 Implement select component in form renderer

- package.json
- yarn.lock
Changed font size from 16px to 19px in Markup component
([link_to_jira_story](https://support.cop.homeoffice.gov.uk/browse/COP-11027))
> change paragraph font size from 16 to 19px

- package.json
- yarn.lock
Updated the version number to 3.6.1
> update version number to 1.9.5

- package.json
- src/docs/ComponentExamples.stories.mdx
- src/docs/ComponentTypes.stories.mdx
- src/models/ComponentTypes.js
- src/utils/Component/getComponent.js
- src/utils/Component/getComponentTests/getComponent.calculation.test.js
- src/utils/Component/isEditable.js
- src/utils/Data/applyFormula.js
- src/utils/Data/applyFormula.test.js
- src/utils/Data/index.js
Description
-------------
A calculation component that performs given supported formula on supplied arguments and display result as a read only 'text' component.
| Supported Formula | Description |
|-------------------|-------------|
| plus | Adds values of argument types in supplied order |
| minus | Subtracts values of argument types in supplied order |
| divide | Divide values of argument types in supplied order |
| multiply | Multiply values of argument types in supplied order |
| Argument types | Description |
|----------------|-------------|
| value | a numeric value, e.g 10, 10.3 |
| field | a reference to field, e.g, currentUser.age |
| formula | a nested formula, e.g percentage calculation |
Example:
-----------
```
{
"id": "cop-firstForm",
"version": "1.0.0",
"name": …
```
> CO-2121: 'calculation' component
